name: maf_mentor
description: Mentor Application

# The following defines the version and build number for your application.
# A version number is three numbers sepaflrated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  pinput: ^0.1.10
  image_picker: ^0.6.2+1
  emoji_picker: ^0.0.2
  url_launcher: ^5.2.0
  fluttertoast: ^3.1.3
  flutter_fadein: ^1.1.1
  progress_dialog: ^1.2.1
  bubble: ^1.1.9+1
  simple_animations: ^1.3.4
  firebase_messaging: ^6.0.12
  page_transition: ^1.1.5
  validate: ^1.7.0
  get_it: ^4.0.0
  flutter_colorpicker: ^0.3.2
  datetime_picker_formfield: ^1.0.0
  shared_preferences: ^0.4.2
  flutter_country_picker: ^0.1.6
  intl: ^0.15.7
  http: ^0.11.3
  strings: ^0.1.2
  dio: ^3.0.9
  cached_network_image: "^0.4.1"
  search_widget: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  http: any
  shared_preferences: any

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/logo.png
    - assets/images/icon.png
    - assets/images/conversation.png
    - assets/images/arrow_box.png
    - assets/images/red_arrow.png
    - assets/images/custom_msg.png
    - assets/images/people.png
    - assets/images/onboarding_bg.png
    - assets/images/donation.png
    - assets/images/preference.png
    - assets/images/sign_out.png
    - assets/images/home_active.png
    - assets/images/group_active.png
    - assets/images/resource_active.png
    - assets/images/schedule_active.png
    - assets/images/home_idle.png
    - assets/images/group_idle.png
    - assets/images/resource_idle.png
    - assets/images/schedule_idle.png
    - assets/images/notification.png
    - assets/images/search.png
    - assets/images/send.png
    - assets/images/smile.png
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy_ExtraBold.otf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Regular.ttf

    - family: Muli
      fonts:
        - asset: assets/fonts/Muli_Bold.ttf

    - family: MuliRegular
      fonts:
        - asset: assets/fonts/Muli_Regular.ttf

    - family: MuliItalic
      fonts:
       - asset: assets/fonts/Muli_Italic.ttf

    - family: MuliLight
      fonts:
       - asset: assets/fonts/Muli_Light.ttf